version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5680:5678"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5680
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - N8N_USER_FOLDER=/home/node/.n8n
      - NODE_ENV=production
      - N8N_CUSTOM_EXTENSIONS=n8n-nodes-form-automation
      - WEBHOOK_URL=${N8N_PROTOCOL:-http}://${N8N_HOST:-localhost}:${N8N_PORT:-5680}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-Asia/Taipei}
      - N8N_RUNNERS_ENABLED=true
      - N8N_METRICS=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-nodes-form-automation:/custom-nodes/n8n-nodes-form-automation
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  auto-service:
    build:
      context: ./auto_node
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - DATABASE_URL=postgresql://user:password@postgres:5432/formdb
      - REDIS_URL=redis://redis:6379
      - FORM_URL=${FORM_URL}
      - EXCEL_FILE=${EXCEL_FILE}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    volumes:
      - ./auto_node:/app
      - /app/node_modules
      - ./data:/app/data
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
      - playwright
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped

  playwright:
    image: mcr.microsoft.com/playwright:v1.42.1-focal
    environment:
      - NODE_ENV=production
      - DISPLAY=:99
    volumes:
      - ./auto_node:/app
    networks:
      - app-network
    command: tail -f /dev/null
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep playwright"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:6
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

volumes:
  n8n_data:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge 